language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env: ROS_DISTRO=indigo
    - os: osx
      osx_image: xcode8
      env: ROS_DISTRO=kinetic
  allow_failures:
    - env: ROS_DISTRO=kinetic
env:
  global:
    # Because virtualized OS X is so slow, and the Travis build VM has only a single core, the
    # build of "desktop" exceeds the 50min limit. If we had sponsorship to get longer build times,
    # we would be able to switch this job to "desktop" or "desktop_full". (Having Gazebo and other
    # stuff from OSRF available bottled would also really help.)
    - ROS_CONFIGURATION=rviz

script:
  - ./install
